!DrivingSim
vJoyID: 1
joystickAxisMinValue: 0
joystickAxisMaxValue: 32767
joystickAxisIncrementValue: 100
momentaryButtonDepressTime: 100
items:
- !Button
  buttonId: 0
  style: DisplayButton
  defaultValue: false
  safeName: GameInfo-GameStarted
  groupName: Game Info
  fullName: Game Started
  textFormatString: >-
    Game Running:
     {0}
  commandTextFormatter: FullName
  iconTextFormatter: YesNo
  telemetryItem: SdkActive
- !Button
  buttonId: 0
  style: DisplayButton
  defaultValue: false
  safeName: GameInfo-GamePaused
  groupName: Game Info
  fullName: Game Paused
  textFormatString: >-
    Game Paused:
     {0}
  commandTextFormatter: FullName
  iconTextFormatter: YesNo
  telemetryItem: Paused
- !Button
  buttonId: 0
  style: DisplayButton
  defaultValue: false
  safeName: Transmission-SelectedGear
  groupName: Transmission
  fullName: Selected Gear
  textFormatString: >-
    Gear:
     {0}
  commandTextFormatter: FullName
  iconTextFormatter: FormattedText
  customTextFormatterType: DesertSunSoftware.LoupedeckVirtualJoystick.TruckingSimPlugin.TransmissionGearFormatter,DesertSunSoftware.LoupedeckVirtualJoystick.TruckingSimPlugin
  telemetryItem: TruckValues.CurrentValues.DashboardValues.GearDashboards
- !Button
  buttonId: 1
  style: MomentaryButton
  defaultValue: false
  safeName: Brakes-ParkingBrake
  groupName: Brakes
  fullName: Parking Brake
  textFormatString: >-
    Parking Brake
     {0}
  commandTextFormatter: FullName
  iconTextFormatter: IconOnly
  telemetryItem: TruckValues.CurrentValues.MotorValues.BrakeValues.ParkingBrake
- !Button
  buttonId: 2
  style: MomentaryButton
  defaultValue: false
  safeName: Engine-EngineStartStop
  groupName: Engine
  fullName: Engine Start/Stop
  textFormatString: >-
    Engine On:
     {0}
  commandTextFormatter: FullName
  iconTextFormatter: IconOnly
  telemetryItem: TruckValues.CurrentValues.EngineEnabled
- !Button
  buttonId: 3
  style: MomentaryButton
  defaultValue: false
  safeName: CruiseControl-CruiseControlOnOff
  groupName: Cruise Control
  fullName: Cruise Control On/Off
  textFormatString: >-
    Cruise Control On:
     {0}
  commandTextFormatter: FullName
  iconTextFormatter: IconOnly
  telemetryItem: TruckValues.CurrentValues.DashboardValues.CruiseControl
- !Button
  buttonId: 4
  style: MomentaryButton
  defaultValue: false
  safeName: Drivetrain-AxleLiftLower
  groupName: Drivetrain
  fullName: Axle Lift/Lower
  textFormatString: >-
    Axle

    Lift On:
     {0}
  commandTextFormatter: FullName
  iconTextFormatter: IconOnly
  telemetryItem: TruckValues.CurrentValues.LiftAxleIndicator
- !Button
  buttonId: 5
  style: MomentaryButton
  defaultValue: false
  safeName: Trailer-TrailerAxleLiftLower
  groupName: Trailer
  fullName: Trailer Axle Lift/Lower
  textFormatString: >-
    Trailer Axle

    Lift On:
     {0}
  commandTextFormatter: FullName
  iconTextFormatter: IconOnly
  telemetryItem: TruckValues.CurrentValues.TrailerLiftAxleIndicator
- !Button
  buttonId: 6
  style: MomentaryButton
  defaultValue: false
  safeName: Drivetrain-DiffLock
  groupName: Drivetrain
  fullName: Diff Lock
  textFormatString: >-
    Diff Lock On:
     {0}
  commandTextFormatter: FullName
  iconTextFormatter: IconOnly
  telemetryItem: TruckValues.CurrentValues.DifferentialLock
- !Button
  buttonId: 7
  style: MomentaryButton
  defaultValue: false
  safeName: Lights-Beacon
  groupName: Lights
  fullName: Beacon
  textFormatString: >-
    Beacon On:
     {0}
  commandTextFormatter: FullName
  iconTextFormatter: IconOnly
  telemetryItem: TruckValues.CurrentValues.LightsValues.Beacon
- !Button
  buttonId: 8
  style: MomentaryButton
  defaultValue: false
  safeName: Lights-FogLights
  groupName: Lights
  fullName: Fog Lights
  textFormatString: >-
    Fog Lights On:
     {0}
  commandTextFormatter: FullName
  iconTextFormatter: IconOnly
  telemetryItem: TruckValues.CurrentValues.LightsValues.AuxFront
- !Button
  buttonId: 9
  style: MomentaryButton
  defaultValue: false
  safeName: Lights-HazardLights
  groupName: Lights
  fullName: Hazard Lights
  textFormatString: >-
    Hazard Lights On:
     {0}
  commandTextFormatter: FullName
  iconTextFormatter: IconOnly
  telemetryItem: TruckValues.CurrentValues.LightsValues.HazardWarningLights
- !Button
  buttonId: 10
  style: MomentaryButton
  defaultValue: false
  safeName: Lights-HighBeams
  groupName: Lights
  fullName: High Beams
  textFormatString: >-
    High Beams On:
     {0}
  commandTextFormatter: FullName
  iconTextFormatter: IconOnly
  telemetryItem: TruckValues.CurrentValues.LightsValues.BeamHigh
- !Button
  buttonId: 11
  style: MomentaryButton
  defaultValue: false
  safeName: Lights-NextLightMode
  groupName: Lights
  fullName: Next Light Mode
  textFormatString: >-
    Headlights On:
     {0}
  commandTextFormatter: FullName
  iconTextFormatter: IconOnly
  telemetryItem: TruckValues.CurrentValues.LightsValues.BeamLow
- !Button
  buttonId: 12
  style: MomentaryButton
  defaultValue: false
  safeName: Camera-Camera1
  groupName: Camera
  fullName: Camera 1
  textFormatString: Camera 1
  commandTextFormatter: FullName
  iconTextFormatter: IconOnly
- !Button
  buttonId: 13
  style: MomentaryButton
  defaultValue: false
  safeName: Camera-Camera2
  groupName: Camera
  fullName: Camera 2
  textFormatString: Camera 2
  commandTextFormatter: FullName
  iconTextFormatter: IconOnly
- !Button
  buttonId: 14
  style: MomentaryButton
  defaultValue: false
  safeName: Camera-Camera3
  groupName: Camera
  fullName: Camera 3
  textFormatString: Camera 3
  commandTextFormatter: FullName
  iconTextFormatter: IconOnly
- !Button
  buttonId: 15
  style: MomentaryButton
  defaultValue: false
  safeName: Camera-Camera4
  groupName: Camera
  fullName: Camera 4
  textFormatString: Camera 4
  commandTextFormatter: FullName
  iconTextFormatter: IconOnly
- !Button
  buttonId: 16
  style: MomentaryButton
  defaultValue: false
  safeName: Camera-Camera5
  groupName: Camera
  fullName: Camera 5
  textFormatString: Camera 5
  commandTextFormatter: FullName
  iconTextFormatter: IconOnly
- !Button
  buttonId: 17
  style: MomentaryButton
  defaultValue: false
  safeName: Camera-Camera6
  groupName: Camera
  fullName: Camera 6
  textFormatString: Camera 6
  commandTextFormatter: FullName
  iconTextFormatter: IconOnly
- !Button
  buttonId: 18
  style: MomentaryButton
  defaultValue: false
  safeName: Camera-Camera7
  groupName: Camera
  fullName: Camera 7
  textFormatString: Camera 7
  commandTextFormatter: FullName
  iconTextFormatter: IconOnly
- !Button
  buttonId: 19
  style: MomentaryButton
  defaultValue: false
  safeName: Camera-Camera8
  groupName: Camera
  fullName: Camera 8
  textFormatString: Camera 8
  commandTextFormatter: FullName
  iconTextFormatter: IconOnly
- !Button
  buttonId: 20
  style: MomentaryButton
  defaultValue: false
  safeName: Camera-NextCamera
  groupName: Camera
  fullName: Next Camera
  textFormatString: Next Camera
  commandTextFormatter: FullName
  iconTextFormatter: IconOnly
- !Button
  buttonId: 21
  style: MomentaryButton
  defaultValue: false
  safeName: CruiseControl-CruiseControlResume
  groupName: Cruise Control
  fullName: Cruise Control Resume
  textFormatString: Cruise Control Resume
  commandTextFormatter: FullName
  iconTextFormatter: IconOnly
- !Button
  buttonId: 22
  style: MomentaryButton
  defaultValue: false
  safeName: Horns-AirHorn
  groupName: Horns
  fullName: Air Horn
  textFormatString: Air Horn
  commandTextFormatter: FullName
  iconTextFormatter: IconOnly
- !Button
  buttonId: 23
  style: MomentaryButton
  defaultValue: false
  safeName: Horns-Horn
  groupName: Horns
  fullName: Horn
  textFormatString: Horn
  commandTextFormatter: FullName
  iconTextFormatter: IconOnly
- !Button
  buttonId: 24
  style: MomentaryButton
  defaultValue: false
  safeName: Misc-ActivateEnter
  groupName: Misc
  fullName: Activate (Enter)
  textFormatString: Activate
  commandTextFormatter: FullName
  iconTextFormatter: IconOnly
- !Button
  buttonId: 25
  style: MomentaryButton
  defaultValue: false
  safeName: Trailer-TrailerAttachDetatch
  groupName: Trailer
  fullName: Trailer Attach/Detatch
  textFormatString: Trailer Attach/Detatch
  commandTextFormatter: FullName
  iconTextFormatter: IconOnly
- !IncreaseDecreaseAdjustment
  increaseButtonId: 26
  decreaseButtonId: 27
  resetButtonId: 28
  safeName: CruiseControl-CruiseControlAdjust
  groupName: Cruise Control
  fullName: Cruise Control Adjust
  textFormatString: Cruise Control
  commandTextFormatter: FullName
  iconTextFormatter: IconOnly
  telemetryItem: TruckValues.CurrentValues.DashboardValues.CruiseControl
- !IncreaseDecreaseAdjustment
  increaseButtonId: 29
  decreaseButtonId: 30
  resetButtonId: 31
  safeName: Transmission-DriveModeAdjust
  groupName: Transmission
  fullName: Drive Mode Adjust
  textFormatString: >-
    Gear:
     {0}
  commandTextFormatter: FullName
  iconTextFormatter: FormattedText
  customTextFormatterType: DesertSunSoftware.LoupedeckVirtualJoystick.TruckingSimPlugin.TransmissionGearFormatter,DesertSunSoftware.LoupedeckVirtualJoystick.TruckingSimPlugin
  telemetryItem: TruckValues.CurrentValues.DashboardValues.GearDashboards
- !IncreaseDecreaseAdjustment
  increaseButtonId: 32
  decreaseButtonId: 33
  resetButtonId: 34
  safeName: RouteAdvisor-RouteAdviserPages
  groupName: Route Advisor
  fullName: Route Advisor Pages
  textFormatString: Route Advisor
  commandTextFormatter: FullName
  iconTextFormatter: IconOnly
- !IncreaseDecreaseAdjustment
  increaseButtonId: 35
  decreaseButtonId: 36
  resetButtonId: 37
  safeName: Camera-CameraChange
  groupName: Camera
  fullName: Camera Change
  textFormatString: Camera Change
  commandTextFormatter: FullName
  iconTextFormatter: IconOnly
- !IncreaseDecreaseAdjustment
  increaseButtonId: 38
  decreaseButtonId: 39
  resetButtonId: 40
  safeName: Wipers-WiperSpeedAdjust
  groupName: Wipers
  fullName: Wiper Speed Adjust
  textFormatString: Wipers
  commandTextFormatter: FullName
  iconTextFormatter: IconOnly
  telemetryItem: TruckValues.CurrentValues.DashboardValues.Wipers
- !FullRangeAdjustment
  axis: Rx
  defaultValue: 16383
  safeName: View-LeftRight
  groupName: View
  fullName: Left/Right
  textFormatString: L/R
  commandTextFormatter: FullName
  iconTextFormatter: IconOnly
