vJoyID: 1
joystickAxisMinValue: 0
joystickAxisMaxValue: 32767
joystickAxisIncrementValue: 100
momentaryButtonDepressTime: 100
buttons:
- buttonId: 0
  style: DisplayButton
  defaultValue: false
  safeName: GameInfo-GameStarted
  groupName: Game Info
  fullName: Game Started
  displayText: >-
    Game Running:
     {0}
  telemetryItem: SdkActive
- buttonId: 0
  style: DisplayButton
  defaultValue: false
  safeName: GameInfo-GamePaused
  groupName: Game Info
  fullName: Game Paused
  displayText: >-
    Game Paused:
     {0}
  telemetryItem: Paused
- buttonId: 0
  style: DisplayButton
  defaultValue: false
  safeName: Engine-EngineStatus
  groupName: Transmission
  fullName: Selected Gear
  displayText: >-
    Auto:
     {0}
  telemetryItem: TruckValues.CurrentValues.DashboardValues.GearDashboards
- buttonId: 1
  style: MomentaryButton
  defaultValue: false
  safeName: Brakes-ParkingBrake
  groupName: Brakes
  fullName: Parking Brake
  displayText: >-
    Parking Brake
     {0}
  telemetryItem: TruckValues.CurrentValues.MotorValues.BrakeValues.ParkingBrake
- buttonId: 2
  style: MomentaryButton
  defaultValue: false
  safeName: Engine-EngineStartStop
  groupName: Engine
  fullName: Engine Start/Stop
  displayText: >-
    Engine On:
     {0}
  telemetryItem: TruckValues.CurrentValues.EngineEnabled
- buttonId: 3
  style: MomentaryButton
  defaultValue: false
  safeName: CruiseControl-CruiseControlOnOff
  groupName: Cruise Control
  fullName: TruckValues.CurrentValues.DashboardValues.CruiseControl
  displayText: >-
    Cruise Control On:
     {0}
  telemetryItem: TruckValues.CurrentValues.DashboardValues.CruiseControl
- buttonId: 4
  style: MomentaryButton
  defaultValue: false
  safeName: Drivetrain-AxleLiftLower
  groupName: Drivetrain
  fullName: Axle Lift/Lower
  displayText: >-
    Axle

    Lift On:
     {0}
  telemetryItem: TruckValues.CurrentValues.LiftAxleIndicator
- buttonId: 5
  style: MomentaryButton
  defaultValue: false
  safeName: Drivetrain-DiffLock
  groupName: Drivetrain
  fullName: Diff Lock
  displayText: >-
    Diff Lock On:
     {0}
  telemetryItem: TruckValues.CurrentValues.DifferentialLock
- buttonId: 6
  style: MomentaryButton
  defaultValue: false
  safeName: Lights-Beacon
  groupName: Lights
  fullName: Beacon
  displayText: >-
    Beacon On:
     {0}
  telemetryItem: TruckValues.CurrentValues.LightsValues.Beacon
- buttonId: 7
  style: MomentaryButton
  defaultValue: false
  safeName: Lights-FogLights
  groupName: Lights
  fullName: Fog Lights
  displayText: >-
    Fog Lights On:
     {0}
  telemetryItem: TruckValues.CurrentValues.LightsValues.AuxFront
- buttonId: 8
  style: MomentaryButton
  defaultValue: false
  safeName: Lights-HazardLights
  groupName: Lights
  fullName: Hazard Lights
  displayText: >-
    Hazard Lights On:
     {0}
  telemetryItem: TruckValues.CurrentValues.LightsValues.HazardWarningLights
- buttonId: 9
  style: MomentaryButton
  defaultValue: false
  safeName: Lights-HighBeams
  groupName: Lights
  fullName: High Beams
  displayText: >-
    High Beams On:
     {0}
  telemetryItem: TruckValues.CurrentValues.LightsValues.BeamHigh
- buttonId: 10
  style: MomentaryButton
  defaultValue: false
  safeName: Lights-NextLightMode
  groupName: Lights
  fullName: Next Light Mode
  displayText: >-
    Headlights On:
     {0}
  telemetryItem: TruckValues.CurrentValues.LightsValues.BeamLow
- buttonId: 11
  style: MomentaryButton
  defaultValue: false
  safeName: Camera-Camera1
  groupName: Camera
  fullName: Camera 1
  displayText: Camera 1
  telemetryItem: 
- buttonId: 12
  style: MomentaryButton
  defaultValue: false
  safeName: Camera-Camera2
  groupName: Camera
  fullName: Camera 2
  displayText: Camera 2
  telemetryItem: 
- buttonId: 13
  style: MomentaryButton
  defaultValue: false
  safeName: Camera-Camera3
  groupName: Camera
  fullName: Camera 3
  displayText: Camera 3
  telemetryItem: 
- buttonId: 14
  style: MomentaryButton
  defaultValue: false
  safeName: Camera-Camera4
  groupName: Camera
  fullName: Camera 4
  displayText: Camera 4
  telemetryItem: 
- buttonId: 15
  style: MomentaryButton
  defaultValue: false
  safeName: Camera-Camera5
  groupName: Camera
  fullName: Camera 5
  displayText: Camera 5
  telemetryItem: 
- buttonId: 16
  style: MomentaryButton
  defaultValue: false
  safeName: Camera-Camera6
  groupName: Camera
  fullName: Camera 6
  displayText: Camera 6
  telemetryItem: 
- buttonId: 17
  style: MomentaryButton
  defaultValue: false
  safeName: Camera-Camera7
  groupName: Camera
  fullName: Camera 7
  displayText: Camera 7
  telemetryItem: 
- buttonId: 18
  style: MomentaryButton
  defaultValue: false
  safeName: Camera-Camera8
  groupName: Camera
  fullName: Camera 8
  displayText: Camera 8
  telemetryItem: 
- buttonId: 19
  style: MomentaryButton
  defaultValue: false
  safeName: Camera-NextCamera
  groupName: Camera
  fullName: Next Camera
  displayText: Next Camera
  telemetryItem: 
- buttonId: 20
  style: MomentaryButton
  defaultValue: false
  safeName: CruiseControl-CruiseControlResume
  groupName: Cruise Control
  fullName: Cruise Control Resume
  displayText: Cruise Control Resume
  telemetryItem: 
- buttonId: 21
  style: MomentaryButton
  defaultValue: false
  safeName: Horns-AirHorn
  groupName: Horns
  fullName: Air Horn
  displayText: Air Horn
  telemetryItem: 
- buttonId: 22
  style: MomentaryButton
  defaultValue: false
  safeName: Horns-Horn
  groupName: Horns
  fullName: Horn
  displayText: Horn
  telemetryItem: 
- buttonId: 23
  style: MomentaryButton
  defaultValue: false
  safeName: Misc-ActivateEnter
  groupName: Misc
  fullName: Activate (Enter)
  displayText: Activate
  telemetryItem: 
- buttonId: 24
  style: MomentaryButton
  defaultValue: false
  safeName: Trailer-TrailerAttachDetatch
  groupName: Trailer
  fullName: Trailer Attach/Detatch
  displayText: Trailer Attach/Detatch
  telemetryItem: 
multiPositionSwitches: []
increaseDecreaseAdjustments:
- increaseButtonId: 25
  decreaseButtonId: 26
  resetButtonId: 27
  safeName: CruiseControl-CruiseControlAdjust
  groupName: Cruise Control
  fullName: Cruise Control Adjust
  displayText: Cruise Control
  telemetryItem: TruckValues.CurrentValues.DashboardValues.CruiseControl
- increaseButtonId: 28
  decreaseButtonId: 29
  resetButtonId: 30
  safeName: Transmission-DriveModeAdjust
  groupName: Transmission
  fullName: Drive Mode Adjust
  displayText: Drive Mode
  telemetryItem: 
- increaseButtonId: 31
  decreaseButtonId: 32
  resetButtonId: 33
  safeName: RouteAdvisor-RouteAdviserPages
  groupName: Route Advisor
  fullName: Route Advisor Pages
  displayText: Route Advisor
  telemetryItem: 
- increaseButtonId: 34
  decreaseButtonId: 35
  resetButtonId: 36
  safeName: Camera-CameraChange
  groupName: Camera
  fullName: Camera Change
  displayText: Camera Change
  telemetryItem: 
- increaseButtonId: 37
  decreaseButtonId: 38
  resetButtonId: 39
  safeName: Wipers-WiperSpeedAdjust
  groupName: Wipers
  fullName: Wiper Speed Adjust
  displayText: Wipers
  telemetryItem: TruckValues.CurrentValues.DashboardValues.Wipers
fullRangeAdjustments:
- axis: Rx
  defaultValue: 16383
  safeName: View-LeftRight
  groupName: View
  fullName: Left/Right
  displayText: L/R
  telemetryItem: 
